### PR TITLE
1.0.12

### PR DESCRIPTION
**Pull request by TheSlowGrowth**
Three tiny fixes.

RE Linnstrument and MPE: The linnstrument doesn't update its current pitchbend value to 0 when a new note is triggered. This resulted in a glitch, where the bend output of the MPE object would still contain the pitchbend value from the last note - meaning the new note was played at the wrong pitch until a new pitchbend message is received.

### CODE REVIEW

**Comment by TheTechnobear** [comment]
that MPE change is incorrect I think.

pitchbend should not be reset on note on, this will not work correctly if you you are using unquantized mode.... with your change, this would make a pitch glitch , as it when initially from zero to the target value.

if you have an issue with this, then this could be  a bug in the MPE implementation on the Linnstrument.
what it should be doing is sending a PB message before note-on to where it wants the note to start.
ask Geert to contact me, if needed, but I think he'll agree ;) 
EDIT: I'll PM you to discuss, and get a midi trace to check exactly your linnstrument issue.

other changes look good, so if you remove mpe change ( you should be able to revert in your fork)  , I will merge. (this is easier for me, than cherry picking your changes ;))

**Comment by TheSlowGrowth** [comment]
Ah, I see. That makes sense. I quickly checked and in fact the Linnstrument is sending a Pitch Bend message right before each note. But for some reason the pitch bend "sticks" - as if that message before the note on is ignored.

Here's what I do to test this: Subpatch in MPE mode with MPE object in it. 4 Voices. I press note "A" and slide to note "C". I release my finger. Now when I strike note "A" multiple times, this is what I hear: "A", "A", "A", "C", "A", "A", "A", "C", "A", "A", "A", "C", ...

I placed a Midi monitor object in my patch and enabled the "Note" and "Bend" checkboxes. I modified the lines 17-21 of the MPE object to look like this:
```
} else if (status == attr_midichannel + MIDI_PITCH_BEND) {
  _bend = (((int)((data2<<7)+data1)-0x2000)<<14) + _xl;
  _pitch = (_note << 21) + ((_bend >> 6)* _bendRange );
  LogTextMessage("PitchBend!");
} else if (status == attr_midichannel + MIDI_CONTROL_CHANGE) {
```

This is what I see in the console window when I strike the Linnstruments pads:
```
PitchBnd ch 8 v  0 v 64
NoteOn  ch 8 n 33 v105
NoteOff ch 8 n 33 v 93
```
This is what I see, when I do a slide:
```
PitchBnd ch 5 v126 v 63
PitchBend!
PitchBnd ch 5 v  0 v 64
PitchBend!
PitchBnd ch 5 v124 v 63
PitchBend!
PitchBnd ch 5 v 58 v 62
PitchBend!
PitchBnd ch 5 v 50 v 62
PitchBend!
```

It seems to me like the bend message isn't transmitted to the MPE object by the firmware when there is currently no note active. Can you reproduce this?

**Comment by TheTechnobear** [comment]
yeah, I was going to ask for a midi dump, as I realised that perhaps axoloti was some where eating the PB if the notes not active.... 

it could be in the note allocation code, I'll go check... if it is I'll fix it, but it wont be fixed till the next axoloti release.
so for now, id suggest to embed the MPE object, and set pb=0...
Id prefer not to change the factory object, as it will be very easy to forget to change it back ;) 

I'll let you know, what I find in the note alloc code.

**Comment by TheTechnobear** [comment]
Ok, I can see the issue... but its a fix I need to be careful with...
basically, I need to not reset the channel on note-off, but if I do this, it will break the sustain handling, so Im going split the active channel vs active sustain handling.
not too hard, but I need to do it when Ive got time to hook up my soundplane and a sustain pedal so I can test it properly.

**Comment by TheSlowGrowth** [comment]
Okay, great. Thank you! I'll stick with the _bend=0 hack for now, as I don't really use the un-quantized mode anyway. Looking forward to the next firmware release.

I have two MPE-synth engines ready to be released to the community. They both have the MPE object embedded in them right now. I had planned to release them in the next days, but I guess it would be better to wait until this is resolved. It would be great if you could let me know when you made the changes.

**Comment by TheTechnobear** [comment]
Unfortunately, this will require an Axoloti release to fix, as its in the generated code.
its likely I'll fix it in next day or so, but we are not planning on releasing a 1.0.13 unless theres a 'showstoppers', so that we can focus on a major release.

so for now, Id release it with an embedded mpe, and you can then change it when the next axo release is out.

(I'll raise against issue on Axoloti, so I dont forget ;))

**Comment by TheTechnobear** [comment]
ok, new issue here...
actually its more complex than I initially thought 
https://github.com/axoloti/axoloti/issues/388

**Pull request merged**
